id: QmRAt6345cpMchvNezDyqn9MxrtmXuGiu3ji72zSAptFae
description: Calls P2P ping and returns the info
tags: []
source: .
trigger:
    type: https
    method: GET
    paths:
        - /ping
domains:
    - p2pDomain
    - testDomain
execution:
    timeout: 30s
    memory: 10MB
    call: ping
