id: QmSxVYL5urSqRj624n2sxPhcXZMqppdpHup9SLWF9hxxNX
description: Returns pong to a ping over p2p
tags: []
source: .
trigger:
    type: p2p
    command: ping
    service: /test/v1
execution:
    timeout: 2s
    memory: 10MB
    call: ping
